name: Build and publish to Github Pages

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v3
          with:
            path: tokir

      -   name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'corretto'
            cache: 'gradle'

      -   name: Setup Gradle
          uses: gradle/gradle-build-action@v2

      -   name: Validate Gradle wrapper
          uses: gradle/wrapper-validation-action@v1

      -   name: Build tokir
          uses: gradle/gradle-build-action@v2
          with:
            arguments: build
            build-root-directory: tokir

      -   name: Build tokir
          uses: gradle/gradle-build-action@v2
          with:
            arguments: jsBrowserWebpack
            build-root-directory: tokir

      -   name: Deploy to GitHub Pages
          if: success()
          uses: crazy-max/ghaction-github-pages@v3
          with:
            target_branch: gh-pages
            build_dir: tokir/build/distributions
            keep_history: false
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}